const get = (req,res)=>{
    res.send(
        [{
            "id": 1,
            "date": "june 27, 2022",
            "title": " Aliya Bhatt and Ranbir Kapoor Expecting their firsht child",
            "Image": "https://images.indianexpress.com/2022/06/ralia.jpg",
            "category": "Bollywood",
            "description": "Alia Bhatt and Ranbir Kapoor are expecting their first child. Taking to Instagram on Monday morning, Alia revealed she was pregnant by sharing a photo of her scan. The big news left their fans ecstatic and congratulations were in order as millions flooded the comments section to wish the couple. Alia and Ranbir tied the knot in 14 April this year.The couple had an intimate wedding celebration at home in the presence of family and close friends. Needless to say, the news has probably left Alia and Ranbir's family, friends and fans over the moon. Taking to Instagram, Alia's pregnancy announcement photo featured husband Ranbir Kapoor in the frame. In the photo, Alia can be seen lying on the hospital bed, with the lovebirds looking at the screen. She captioned the photo, Our baby ….. coming soon.  While the first photo was of Alia and Ranbir, the second picture featured a lion, a lioness and their cub. Probably a photo that Ranbir clicked on one of the many Safari trips he took with wife Alia Bhatt prior to their wedding.Recently, during the trailer launch of Shamshera, Ranbir spoke about Alia's presence in his life while referring to his famous movie dialogue. Revealing Alia Bhatt’s reaction to Shamshera’s trailer, Ranbir Kapoor said, “Alia had seen the teaser and loved it. She is in London right now, so once she wakes up she will see the trailer.He further added,Films aside, this is a big year for me as I even got married. I always said that we need tangdi kebab, and not dal chawal in life. But with experience I can say that nothing better than Dal Chawal. Alia is the tadka in dal chawal, the achar with it, she is everything and I could not have asked for a better partner in my life.Here's wishing Alia and Ranbir a hearty congratulations."
          },
          {
            "id": 2,
            "date": "January 28, 2022",
            "title": "Steven Spielberg had introduced Aamir Khan to Tom Hanks as ‘James Cameron of India’; Tom revealed that he has seen 3 Idiots as many as 3 times!",
            "Image": "https://stat1.bollywoodhungama.in/wp-content/uploads/2022/05/Steven-Spielberg-had-introduced-Aamir-Khan-to-Tom-Hanks-as-%E2%80%98James-Cameron-of-India%E2%80%99-Tom-revealed-that-he-has-seen-3-Idiots-as-many-as-3-times-2.jpg",
            "category": "Bollywood",
            "description": "It has recently come to light that Tom Hanks is an admirer of Aamir Khan as well. Aamir Khan happened to meet him somewhere in 2014 or 2015 when he flew down to Germany to have a meeting with acclaimed filmmaker Steven Spielberg. It so happened that Aamir Khan wished to remake Forrest Gump (1994) whose rights rested with its director Robert Zemeckis. Robert, however, refused to meet Aamir. Aamir tried a lot to set up the meeting but in vain. Left with no choice, he decided to meet Steven Spielberg, who was then shooting for his film Bridge Of Spies (2015). Interestingly, the film starred Tom Hanks, who also starred in Forrest Gump and whose role Aamir wanted to essay in the remake. Robert Zemeckis held Spielberg in high regard. As a result, Aamir felt that if Steven Spielberg would convince Robert, the latter would part with the remake rights of Forrest Gump. Aamir Khan reached the sets of Bridge Of Spies and met Steven Spielberg along with Tom Hanks. Steven Spielberg introduced Aamir to Tom Hanks as ‘James Cameron of India’. This is because according to the filmmaker, just like how James Cameron breaks his own box office records, so does Aamir! Tom Hanks, however, made it clear that he knows Aamir very well. He also admitted that he loved Aamir’s 2009 film 3 Idiots and that he has seen it as many as 3 times! Aamir Khan then told Steven Spielberg about his predicament about Robert Zemeckis. To which Spielberg told Aamir that his relationship with Zemeckis was like that of a father and a son. And like most fathers and sons, they don’t always get along well! He also revealed to Aamir that Robert Zemeckis was refusing to meet the superstar as he didn’t want to say ‘no’ to Aamir’s face. Nevertheless, Aamir Khan kept on trying. At last, he won the remake rights. The remake of Forrest Gump came to be known as Laal Singh Chaddha. It is all set to release on August 11, 2022, and is one of the most awaited films of the year."
          },
          
          {
            "id": 3,
            "date": "May 23, 2022",
            "title": "FAKE photo of Shah Rukh Khan, Salman Khan and Hrithik Roshan from Karan Johar's 50th birthday bash goes viral on the internet",
            "Image": "https://static.toiimg.com/thumb/msid-91868025,width-1070,height-580,overlay-toi_sw,pt-32,y_pad-40,resizemode-75,imgsize-22362/91868025.jpg",
            "category": "Bollywood",
            "description": "Karan Johar’s 50th birthday bash was a star-studded affair with the who’s who of Bollywood making their presence felt. Pictures and videos from the grand party are still doing the rounds on social media. playing near you in IMAX then this is the next best way to watch it. Fucken @RRRMovie is insane.When the team of RRR responded to thank Oswalt, he replied, “You guys are out of your f**king minds, you should not be allowed to make films, and I can’t wait to see what you do next.RR is a period drama starring Ram Charan and NTR Jr and follows two revolutionaries - Alluri Sitarama Raju and Komaram Bheem as they go up against the British rule in India. The film was released on March 24 this year. Since then, it has garnered significant buzz. It also kickstarted a debate on the way pan-India films are perceived. These Bollywood superstars coming together for a picture like this is surely a sight for sore eyes. However, much to the disappointment of their fans, the photo is an edited one and is clearly a fake."
          },
          {
            "id": 4,
            "date": "January 23, 2022",
            "title": "Shah Rukh Khan, Salman Khan and Madhuri Dixit's selfie has fans recalling Hum Tumhare Hai Sanam",
            "Image": "https://th.bing.com/th/id/OIP.jl_1HMS7qyCQVvzHay3n-wHaHG?w=250&h=250&c=7&rs=1&o=5&dpr=1.25&pid=1.1",
            "category": "Bollywood",
            "description": "Talking to Bollywood Hungama about her past films, she said, “I was not happy. Sometimes you work against your wishes, just because you have to keep working. When the thought of out of sight is out of mind takes over, you don't have many choices. Today it is quite easy for me to sit and say that instead of doing those films I should have learned kung fu in China or anything else. Today it is easy for me to say that. But it wasn't the same 6-7 years ago. Back then I was just trying to understand myself and wondering what happened. My first film did well and everyone even appreciated it. But why weren't certain choices given to me after that? Then I get the answer that you should do the kind of films which have songs, and if the song is a hit, the film also works. But I didn't think that way. It worked for somebody, but may not work for me. But you still want to try because somebody is saying, either someone who is experienced or someone from your team. They come from a  place where they mean well to you.She further said, “Then you are told that only when you work with certain names, and that you need to get more films with the really big stars to be out there. Now, that may also be true. But I did that, but it didn't work for me. One of them had a very good role also. I am talking about Kaabil but unfortunately, that was also like ‘aapka role usme utna hi tha (you had a small role). But I could not figure out why people were thinking like that. Why aren't they thinking about how I performed in that film. We often talk about films made outside of our country where big stars do small roles in big films. Anyway, it is easy to talk about this today. But back then it sounded like you are complaining about every trivial thing. It is better to take a breather and reshuffle everything."
          }]
    )
}

module.exports.ApiController = get